### ISSUE TITLE
Missing *.UU files

### ISSUE THREAD

**Issue by wojdyr** [tlhrigaku/d-star-trek#2]
Makefiles in DTDISPLAY and DTCOLLECT have rules to make gifs from UU files, e.g.
```
EditImageView.gif:      EditImageView.UU
        uudecode $^
```

but neither UUs nor gifs are present in the repository. Can they be added?

**Comment by tlhrigaku** [comment]
I've added the uuencoded files.

**Comment by wojdyr** [comment]
Thanks! But they are not in the repo yet?

**Comment by wojdyr** [comment]
@tlhrigaku you need to do "git push"?

@graeme-winter, @Anthchirp: we're getting closer to compiling d*TREK GUI :-)

**Comment by wojdyr** [comment]
@tlhrigaku no commit was made this year and the UU files are clearly not added. Could you re-open this issue?

**Comment by tlhrigaku** [comment]
They are there now. Not sure why the desktop git version did not push them previously.

**Comment by wojdyr** [comment]
thanks!
