### ISSUE TITLE
missing pinet.h

### ISSUE THREAD

**Issue by jamesmbell** [tlhrigaku/d-star-trek#3]
I'm trying to compile d*TREK on OSX (10.12.3). After making some modifications to CPPFLAGS in the Makefiles to locate X11 and Xm headers, I'm encountering the following error:

```
/usr/bin/g++ -DIRIX -Wno-non-template-friend -DBINARY_NOT_BIN -c -g -O1 -DDEMO_LICENSE -I. -I../DTDISPLAY -I. -L../DTDISPLAY -L.  -L/usr/lib32/mips3 -I/usr/local/include -I/usr/include -o dtfind.o dtfind.cpp
clang: warning: argument unused during compilation: '-L../DTDISPLAY'
clang: warning: argument unused during compilation: '-L.'
clang: warning: argument unused during compilation: '-L/usr/lib32/mips3'
warning: unknown warning option '-Wno-non-template-friend'; did you mean '-Wno-unsupported-friend'?
      [-Wunknown-warning-option]
In file included from dtfind.cpp:47:
In file included from ./DTMainFind.h:51:
In file included from ./DTMain.h:70:
./DTCoreSocket.h:50:10: fatal error: 'pinet.h' file not found
#include "pinet.h"  // ptypes stuff
         ^
1 warning and 1 error generated.
make: *** [dtfind.o] Error 1
```

`pinet.h` does not appear to be present in this repository. Does anyone know where I can find it? Perhaps it was removed during the transition from google code to github?

**Comment by tlhrigaku** [comment]
Per the wiki (https://github.com/tlhrigaku/d-star-trek/wiki/Building-d*TREK), you need to download the PTypes and CBF libraries. Links for these libraries are given on the wiki page.

**Comment by jamesmbell** [comment]
Sorry, I completely overlooked the wiki pages. Thanks!
